global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

scrape_configs:
  - job_name: fluxum-backend
    static_configs:
      - targets:
          - host.docker.internal:3000   
        labels:
          app: fluxum
